workflows:
  default-workflow:
    name: YT Mutual Workflow
    environment:
      flutter: stable
    scripts:
      - name: Clean old android folder
        script: rm -rf android
      - name: Generate Android Platform Files
        script: flutter create . --platforms=android
      - name: Install dependencies
        script: flutter pub get
      - name: Build App Bundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
