workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Re-generate Android folder
        script: |
          rm -rf android
          flutter create . --platforms=android
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
